create TABLE IF NOT EXISTS games (
   id SERIAL PRIMARY KEY
 , name TEXT NOT NULL
 , system TEXT NOT NULL
 , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

create TABLE IF NOT EXISTS sessions (
   id SERIAL PRIMARY KEY
 , gameID INT REFERENCES games(id)
 , start_time TIMESTAMP WITH TIME ZONE NOT NULL
 , end_time TIMESTAMP WITH TIME ZONE NOT NULL
);
